name: feature/next PR test

on:
  pull_request:
    branches: [ feature/next ]

jobs:
  test:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v2
        run: |
          npm install,
          npm run lint,
          npm run test,
          npm run build.
