name: Review Branch Testing

on:
  push:
    branches: [ review/* ]

jobs:
  test:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v2

      - name: Run a multi-line script
        run: |
          npm install
          npm run lint
          npm run test
